### ISSUE TITLE
Wormadam-Sandy and Wormadam-Trash level up sets don't work correctly

### ISSUE THREAD

**Issue by UbeHalaya-Speg** [EverOddish/pokemon-showdown#4]
You can't teach either wormadam Rock Blast or Mirror Shot or TMs not compatible with Wormadam-leaf cloak.  They also can't learn Razor leaf.  non-Leaf Wormadam in general is a bit buggy.

**Comment by EverOddish** [comment]
Fixed for next server reboot.
